default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV.fetch('API_DATABASE_USER') %>
  password: <%= ENV.fetch('API_DATABASE_PASS') %>
  host: <%= ENV.fetch('API_DATABASE_HOST') %>
  pool: <%= ENV.fetch('API_DATABASE_POOL') %>

development:
  <<: *default
  database: challenge-api_development

test:
  <<: *default
  database: challenge-api_test

production:
  <<: *default
  database: <%= ENV.fetch('API_DATABASE_NAME') %>
