default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: ''
  host: localhost
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: challenge-api_development

test:
  <<: *default
  database: challenge-api_test

production:
  <<: *default
  database: challenge-api_production
  username: challenge-api
  password: <%= ENV['CHALLENGE-API_DATABASE_PASSWORD'] %>
